<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sridher" failures="1" tests="2" name="com.api.tests.ApiTest" time="3.465" errors="0" timestamp="2024-10-17T02:16:26 IST" skipped="0">
  <testcase classname="com.api.tests.ApiTest" name="applePost" time="3.179">
    <system-out>
      <![CDATA[Connecting to EndPoint
Passed: id is successfully Generated with non null value
Passed: createdDate is successfully Generated with non null value
Passed: name is successfully matched
Passed: price is successfully matched
Passed: year is successfully matched
Passed: Hard Disk Size is successfully matched
Passed: cpu Model is successfully matched]]>
    </system-out>
  </testcase> <!-- applePost -->
  <testcase classname="com.api.tests.ApiTest" name="applePost_Fail" time="0.286">
    <failure message="expected [Apple Max Pro 1TB] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Apple Max Pro 1TB] but found [null]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.api.tests.ApiTest.applePost_Fail(ApiTest.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Connecting to EndPoint
Passed: id is successfully Generated with non null value
Passed: createdDate is successfully Generated with non null value
Failed: Error Ocuured expected [Apple Max Pro 1TB] but found [null]]]>
    </system-out>
  </testcase> <!-- applePost_Fail -->
  <system-out>
    <![CDATA[Connecting to EndPoint
Passed: id is successfully Generated with non null value
Passed: createdDate is successfully Generated with non null value
Passed: name is successfully matched
Passed: price is successfully matched
Passed: year is successfully matched
Passed: Hard Disk Size is successfully matched
Passed: cpu Model is successfully matched
Connecting to EndPoint
Passed: id is successfully Generated with non null value
Passed: createdDate is successfully Generated with non null value
Failed: Error Ocuured expected [Apple Max Pro 1TB] but found [null]]]>
  </system-out>
</testsuite> <!-- com.api.tests.ApiTest -->
